// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-OXz2zPK2WfU2uPMvYI89eky9VGIOpfY',
    appId: '1:572718114329:web:bb7d9c5810cb7a0809ec88',
    messagingSenderId: '572718114329',
    projectId: 'scholar-chat-app-c68a2',
    authDomain: 'scholar-chat-app-c68a2.firebaseapp.com',
    storageBucket: 'scholar-chat-app-c68a2.appspot.com',
    measurementId: 'G-XC3RJXV434',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQjKisgiB4u4LClP9nT6sMTsMkQkC8qE4',
    appId: '1:572718114329:android:d8cee287b7b2e9a409ec88',
    messagingSenderId: '572718114329',
    projectId: 'scholar-chat-app-c68a2',
    storageBucket: 'scholar-chat-app-c68a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvLmOstGg7aVUStf38GmCz8sr3jKvBJqU',
    appId: '1:572718114329:ios:85ebb61c9b3bd93009ec88',
    messagingSenderId: '572718114329',
    projectId: 'scholar-chat-app-c68a2',
    storageBucket: 'scholar-chat-app-c68a2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvLmOstGg7aVUStf38GmCz8sr3jKvBJqU',
    appId: '1:572718114329:ios:d20c55867c0c5f6809ec88',
    messagingSenderId: '572718114329',
    projectId: 'scholar-chat-app-c68a2',
    storageBucket: 'scholar-chat-app-c68a2.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
